config/routes.rb
Rails.application.routes.draw do

  resources :producers

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  validates :name, :description, :priority, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  def index
    @producers = Producer.all
  end

  def create
    @producer = Producer.create(producer_params)
    if @producer.errors.any?
      render :new
    else
      redirect_to producer_path(@producer)
    end
  end

  def show
    @producer = Producer.find(params[:id])
  end

  def new
    @producer = Producer.new
  end

  def edit
    @producer = Producer.find(params[:id])
  end

  def destroy
  end

  def update
    @producer = Producer.find(params[:id])
    @producer.update(producer_params)
    redirect_to producer_path(@producer)
  end

  private
  def producer_params
    params.require(:producer).permit(:name, :description, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails31Jan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>

    <br>
    <% if params[:action] == "index" %>
      <%= link_to "new producer", new_producer_path, class: "btn btn-default" %>
    <% elsif params[:action] == "new" %>
      <%= link_to "home", producers_path, class: "btn btn-default" %>
    <% else %>
      <%= link_to "home", producers_path, class: "btn btn-default" %>
      <%= link_to "new producer", new_producer_path, class: "btn btn-default" %>
    <% end %>
  </div>
</body>
</html>

app/views/producers/_form.html.erb
  <% if @producer.errors.any? %>
  <div class="alert alert-warning" role="alert">
    <p>we got an error sir!</p>
    <% if @producer.errors[:name].present? %>
      You need to put in a name
    <% end %>
  </div>
<% end %>

<%= form_for(@producer) do |f| %>
  <%= f.text_field :name, placeholder: 'name' %>
  <br><%= f.text_field :description, placeholder: 'description' %>
  <br><%= f.number_field :priority, placeholder: 'priority' %>
  <br><%= f.submit %>
<% end %>

app/views/producers/create.html.erb
<h1>Producers#create</h1>
<p>Find me in app/views/producers/create.html.erb</p>

app/views/producers/destroy.html.erb
<h1>Producers#destroy</h1>
<p>Find me in app/views/producers/destroy.html.erb</p>

app/views/producers/edit.html.erb
<h2> edit </h2>

<%= render 'form' %>

app/views/producers/index.html.erb
<div class="col-md-12">
  <h1>Producers#index</h1>
  <p>Here I will show all producers</p>

  <ol>
  <% @producers.each do |producer| %>
    <li>
      <%= link_to "#{producer.name}: #{producer.description}", producer_path(producer) %>
    </li>
  <% end %>
  </ol>
</div>

app/views/producers/new.html.erb
<h1>Producers#new</h1>
<p>Find me in app/views/producers/new.html.erb</p>


  <% if @producer.errors.any? %>
  <div class="alert alert-warning" role="alert">
    <p>we got an error sir!</p>
    <% if @producer.errors[:name].present? %>
      You need to put in a name
    <% end %>
  </div>
<% end %>

<%= render 'form' %>

app/views/producers/show.html.erb
<h1> Showing producer </h1>

name: <%= @producer.name.capitalize %><br>
description: <%= @producer.description.capitalize %><br>
priority: <%= @producer.priority %>

<%= link_to "edit", edit_producer_path(@producer) %>

app/views/producers/update.html.erb
<h1>Producers#update</h1>
<p>Find me in app/views/producers/update.html.erb</p>